//= require jquery
//= require jquery.ui.all
//= require jquery.mousewheel
//= require antiscroll
//= require environment
//= require ember-appkit
//= require bootstrap
//= require list-view
//= require jquery.slimscroll
//= require moment-with-langs
//= require daterangepicker
//= require ember-table
//= require_self
//= require_tree ./adapters
//= require_tree ./serializers
//= require router
//= require_tree ../app
//= require_tree ./initializers

window.App = require('app').default.create();
